# Promise.resolve()
产生一个成功Promise
```js
new Promise((resolve, reject) => {
  resolve('ok')
})
```
如上产生一个简单的成功态的Promise实例，要写很啰嗦的一大段代码，那有什么简单的办法搞定上面的东西吗？答案是：Promise的静态方法resolve

```js
class Promise {
  ...
  /**
   * 产生一个成功态的Promise实例
   * @param {成功的结果值} value 
   */
  static resolve (value) {
    return new Promise(resolve => resolve(value))
  }
}
```

# Promise.reject()
产生一个失败Promise
```js
class Promise {
  ...
  /**
   * 产生一个失败态的Promise实例
   * @param {失败的原因} reason 
   */
  static reject (reason) {
    return new Promise((resolve, reject) => reject(reason))
  }
}
```

# Promise.prototype.catch()
相当于没有提供onFulfilled回调函数的then方法
```js
class Promise {
  catch (onRejected) {
    return this.then(null, onRejected)
  }
}
```

# Promise.prototype.finally()
finally()方法返回一个Promise。在promise结束时，无论结果是fulfilled或者是rejected，都会执行指定的回调函数。这为在Promise是否成功完成后都需要执行的代码提供了一种方式。

这避免了同样的语句需要在then()和catch()中各写一次的情况。

具体解释参见[MDN](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally)

其具有以下特点：
* 如果成功则调用下一个Promise的成功回调，如果失败则调用下一个Promise的失败回调
* 如果传给finally的函数参数的返回值为一个Promise，则会等待这个Promise的executor中执行完成再调用下一个Promise的then

```js
class Promise {
  ...
  finally (callback) {
    return this.then(value => {
      return Promise.resolve(callback()).then(() => value)
    }, reason => {
      return Promise.resolve(callback()).then(() => { throw reason })
    })
  }
}
```

# Promise.prototype.all()

